- name: catalogue server
  hosts: catalogue
  become: yes
  tasks: 
  - name: disable old nodejs
    ansible.builtin.shell: dnf module disable nodejs -y ; dnf module enable nodejs:18 -y
      name: nodejs
      state: present