- name: catalogue server creation
  hosts: catalogue
  become: yes
  tasks: 
  - name: disable old nodejs
    ansible.builtin.shell: dnf module disable nodejs -y ; dnf module enable nodejs:18 -y
  
  - name: install nodejs
    absible.builtin.package:
      name: nodejs
      state: present
      

