- name: shipping
  hosts: shipping
  become: yes
  tasks:
  - name: configure YUM erlang Repos
    ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh | bash

  - name: configure yum Rabbitmq repos
    ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh | bash

  - name: install rabbitmq server
    ansible.builtin.package: 
      name: rabbitmq-server
      state: present

  - name: start and enable rabbitmq server
    ansible.builtin.package: 
      name: rabbitmq-server
      state: restarted
      enabled: yes

  - name: create rabbitmq user
    ansible.builtin.shell: rabbitmqctl add_user roboshop roboshop123

  - name: set permissions
    ansible.builtin.shell: rabbitmqctl set_permissions -p / roboshop ".*" ".*" ".*"
