- name: creating web
  hosts: web
  become: yes
  tasks:
  - name: install nginx
    ansible.builtin.package:
      name: nginx
      state: present

  - name: Recursively remove directory
    ansible.builtin.file:
      path: /usr/share/nginx/html/
      state: absent

  - name: Create a directory for app
    ansible.builtin.file:
      path: /usr/share/nginx/html/
      state: directory
  
  - name: Copy file with owner and permissions
    ansible.builtin.copy:
      src: https://roboshop-builds.s3.amazonaws.com/web.zip
      dest: /tmp/web.zip

  - name: unzip
    ansible.builtin.unarchive:
      src: /tmp/web.zip
      dest: /usr/share/nginx/html
      remote_src: yes

  - name: Copy roboshop configuration
    ansible.builtin.copy:
      src: roboshop.conf
      dest: /etc/nginx/default.d/roboshop.conf

  - name: restart nginx
    ansible.builtin.package:
      name: nginx
      state: restarted